package com.adv;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 * Die Klasse UserDataAccess ist für alle Datenbankoperationen zustaendig, die mit Benutzern zu tun haben.
 * @author Advik Vattamwar
 * @version 10.01.2026
 */
public class UserDataAccess {

    private final Database db = new Database();

    /**
     * Sucht einen einzelnen Benutzer anhand seines eindeutigen Benutzernamens.
     * @param username Der Benutzername, nach dem gesucht werden soll.
     * @return Ein User-Objekt, wenn gefunden, sonst null.
     */
    public User findUserByUsername(String username) {
        String sql = "SELECT * FROM users WHERE username = ? LIMIT 1";

        try (Connection conn = db.connect();
             PreparedStatement preparedStatement = conn.prepareStatement(sql)) {

            preparedStatement.setString(1, username);

            try (ResultSet rs = preparedStatement.executeQuery()) {
                if (rs.next()) {
                    return mapRowToUser(rs);
                }
            }
        } catch (SQLException e) {
            System.err.println("Error finding user by username: " + e.getMessage());
        }
        // Wenn kein Nutzer gefunden wurde oder ein Fehler aufgetreten ist, gib NULL zurück
        return null;
    }

    /**
     * Sucht einen Benutzer anhand seiner userID.
     * @param userId Die ID des Users.
     * @return Ein User-Objekt, wenn gefunden, sonst null.
     */
    public User findUserById(String userId) {
        String sql = "SELECT * FROM users WHERE user_id = ?::uuid";

        try (Connection conn = db.connect();
        PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
            preparedStatement.setString(1, userId);

            try(ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) return mapRowToUser(resultSet);
            }


        } catch (SQLException e) {
            System.out.println("Error finding user by userId: \n" + e.getMessage());
        }
        return null;
    }

    /**
     * Findet alle Benutzer, die eine bestimmte Rolle haben (z.B. alle "student" oder "teacher").
     * @param role Die Rolle, nach der gefiltert werden soll (student, teacher, admin).
     * @return Eine ArrayList mit allen gefundenen User-Objekten.
     */
    public ArrayList<User> findUsersByRole(String role) {
        ArrayList<User> users = new ArrayList<>();
        String sql = "SELECT * FROM users WHERE role = ?::roles"; // "::roles" ist dafür da, den String in den ENUM Typ zu übersetzen

        try (Connection conn = db.connect();
        PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
            preparedStatement.setString(1, role);

            try(ResultSet resultSet = preparedStatement.executeQuery()) {
                while (resultSet.next()) {
                    users.add(mapRowToUser(resultSet));
                }
            }

        } catch (SQLException e) {
            System.err.println("Error finding unsers by role: " + e.getMessage());
        }
        return users;
    }

    /**
     * Erstellt einen neuen Benutzer in der Datenbank.
     * @param user Das User-Objekt, das gespeichert werden soll.
     * @return true, wenn das Einfügen erfolgreich war, sonst false.
     */
    public boolean createUser(User user) {
        // Note: ID generated by Database
        String sql = "INSERT INTO users (first_name, last_name, username, password_hash, role) VALUES (?, ?, ?, ?, ?::roles)";

        try (Connection conn = db.connect();
             PreparedStatement preparedStatement = conn.prepareStatement(sql)) {
            preparedStatement.setString(1, user.getFirstName());
            preparedStatement.setString(2, user.getLastName());
            preparedStatement.setString(3, user.getUsername());
            preparedStatement.setString(4, user.getPasswordHash());
            preparedStatement.setString(5, user.getRole());

            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;

        } catch (SQLException e) {
            System.err.println("Error creating user: " + e.getMessage());
            return false;
        }
    }

    /**
     * Aktualisiert den Passwort Hash eines Benutzers.
     *
     * @param userId          Die ID des Benutzers, dessen Passwort geändert werden soll.
     * @param newPasswordHash Der neue, bereits gehashte Passwort.
     * @return true, wenn das Aktualisieren erfolgreich war, sonst false.
     */
    public boolean updatePassword(String userId, String newPasswordHash) {
        String sql = "UPDATE users SET password_hash = ? WHERE user_id = ?::uuid";

        try (Connection conn = db.connect();
        PreparedStatement preparedStatement = conn.prepareStatement(sql)) {

            preparedStatement.setString(1, newPasswordHash);
            preparedStatement.setString(2, userId);

            int affectedRows = preparedStatement.executeUpdate();
            return affectedRows > 0;

        } catch (SQLException e) {
            System.err.println("Error updating user password: " + e.getMessage());
            return false;
        }
    }

    /**
     * Hilfsmethode, die eine Zeile aus dem ResultSet in ein User-Objekt macht.
     *
     * @param resultSet Das ResultSet, das auf der aktuellen Zeile steht.
     * @return Ein neues User-Objekt mit den Daten aus der Datenbankzeile.
     * @throws SQLException Wenn ein SQLFehler beim Zugriff auf die Datenbank auftritt.
     */
    private User mapRowToUser(ResultSet resultSet) throws SQLException {
        return new User(
                resultSet.getString("user_id"),
                resultSet.getString("first_name"),
                resultSet.getString("last_name"),
                resultSet.getString("username"),
                resultSet.getString("password_hash"),
                resultSet.getString("role")
        );
    }
}